---
 # Fail if profile_name is not specified
- name: fail all further operations if profile_name
  fail: msg="AppArmor profile to create is not specified"
  when: profile_name == "None"

# Create AppArmour profiles directory for containers
- file: path={{ profile_dir }} state=directory mode=0755

# Check if the tunables/global exist
- name: Check if the tunables/global exist
  stat: path='/etc/apparmor.d/tunables/global'
  register: tunables_global

# Check if abstractions/base exist
- name: Check if abstractions/base exist
  stat: path='/etc/apparmor.d/abstractions/base'
  register: abstractions_base

# Get apparmor_parser version
- name: Get apparmor_parser version
  shell: /sbin/apparmor_parser --version | grep version | cut -d " " -f 4
  register: apparmor_parser_version
  changed_when: false
  
# Generate profile config using template
- name: Create AppArmor profile
  template: src='profile.j2' dest='{{ profile_dir }}/{{ profile_name }}'

# Apply generated config
- name: Apply generated config
  shell: /sbin/apparmor_parser -r -W {{ profile_name| quote }}
  changed_when: false
  tags:
    - apply_profile
